### ISSUE TITLE
milkshake spelled 'milksake' in 'Deeper Understanding of mapStateToProps' section 

### ISSUE THREAD

**Issue by EricLum** [learn-co-curriculum/review-map-state-to-props-readme#3]
just spelling error.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
