### ISSUE TITLE
code doesn't initially work

### ISSUE THREAD

**Issue by charlie763** [learn-co-curriculum/review-map-state-to-props-readme#31]
In app.js... this.props.store.dispatch is called in both event handlers. since there is no mapDispatchtoProps method initially, this results in an error. changing the code to this.props.dispatch gets it to work as connect() provides a default dispatch prop.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
