### ISSUE TITLE
× TypeError: Cannot read property 'dispatch' of undefined

### ISSUE THREAD

**Issue by zkobrinsky** [learn-co-curriculum/review-map-state-to-props-readme#34]
this.props.store.dispatch... needs to be changed to this.props.dispatch

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
