### ISSUE TITLE
missing dispatch method in this lab

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/review-map-state-to-props-readme#6]
The lab states: "You will notice that if it wasn't for the dispatch method (and in a later lesson we will remove that as well), our component would have no knowledge of our store,"

The code calls dispatch() but I don't see defined anywhere. 

Thanks!

**Comment by ValerieHMoore** [comment]
If you're going to keep the sentence above, you need to change "wasn't" to the subjunctive:
"You will notice that if it weren't for the dispatch method...."

Thank you.

**Comment by kodyclemens** [comment]
> The lab states: "You will notice that if it wasn't for the dispatch method (and in a later lesson we will remove that as well), our component would have no knowledge of our store,"
> 
> The code calls dispatch() but I don't see defined anywhere.
> 
> Thanks!

The dispatch method is in the handleOnClick methods for each button.

**Comment by maxwellbenton** [comment]
Hi @emikojima and @ValerieHMoore,

Thank you for providing feedback on this lesson. We've updated this paragraph in question to more clearly convey the concept of using `mapDispatchToProps` to separate components from the store
