### ISSUE TITLE
Changing

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/review-map-state-to-props-readme#8]
Kindly fix the spelling in the first word of this sentence:
"Chaiging the function back to mapStateToProps(), let's pay special attention to the return value to that function:"

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for spotting this issue and providing feedback.

We have fixed the spelling of 'Changing' in this readme
