### ISSUE TITLE
More grammar stuff

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/review-map-state-to-props-readme#9]
These two sentences should be one sentence; change the period to a comma and start "Then" with a small t. I would also remove the "that" after "separated,":
"It also means that because all of our Redux is separated, that if we wanted to add in changes to our application to be mobile by using React Native. Then our Redux logic would largely stay the same."

This is a run-on sentence:
"Because normally, what we are doing is taking a part of the store's state and porting it to become props of the relevant component, we say that we are taking part of the state, and mapping them as props to the component, thus the name mapStateToProps."

Suggested rewrite:
"Because we are taking a part of the store's state and porting it to become props of the relevant component, we say that we are mapping it as props to the component, thus the name mapStateToProps."

Thank you.

**Comment by maxwellbenton** [comment]
Hi @ValerieHMoore,

Thank you for spotting this issue and providing feedback.

We have updated these sentences to based on your suggestions. Thank you for all the feedback you've provided!
